[template]
src   = "haproxy.cfg.tmpl"
dest  = "/etc/haproxy/haproxy.cfg"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "global",
  "hosts",
  "upstreams"
]
check_cmd = "/bin/bash -c '/usr/sbin/haproxy -c -f {{.src}} 1>/var/log/haproxy-check.log 2>&1'"
reload_cmd = "/usr/sbin/haproxy-reload.sh"