[template]
src   = "haproxy.cfg.tmpl"
dest  = "/etc/haproxy/haproxy.cfg"
uid = 0
gid = 0
mode  = "0644"
keys = [
  "global",
  "hosts",
  "upstreams"
]
check_cmd = "/usr/sbin/haproxy -c -f {{.src}}"
reload_cmd = "/etc/init.d/haproxy reload"